### ISSUE TITLE
Setting rich text

### ISSUE THREAD

**Issue by mbresson** [360EntSecGroup-Skylar/excelize#172]
Hi,
first, thanks creating for this library, it's very useful.

I would like to know if it's possible to have rich text inside a cell? What I mean by rich text is text with a rich format, for instance "Hello **world**" where world is bold but Hello isn't. I have tried to dabble with SetCellStr and SetCellDefault with content such as `"Hello <font style='weight:700'>world</font>"` (I don't know a lot about XLSX format so my example may be wrong) but the cell value ends up escaped (with SetCellDefault too).

Thanks!

**Comment by xuri** [comment]
Thanks for your issue, reference issue #69 (set multiline texts to cells support) and #100.  I have added this feature request to the [Roadmap](https://github.com/360EntSecGroup-Skylar/excelize/wiki).

**Comment by mbresson** [comment]
Thanks
Do you think there is a lot of work required to complete this feature, and do you already have a clear idea of how to implement it? Maybe I could lend you a hand depending on what's needed

**Comment by xuri** [comment]
Welcome! The cell's text style (include font, size, color, bold, underline, etc.) is stored in the file: `xl/sharedStrings.xml` and the data structure of this file is defined in  `xmlSharedStrings.go`. In order to implement this feature, we need to refactor functions: `GetCellValue()` and `SetCellValue()`, change the interface to make them get/set the value and style from the `xl/sharedStrings.xml`, and add new function `SetCellValueWithStyle()`.

**Comment by Astronomican** [comment]
hi,will this feature be implemented in the future?

**Comment by xuri** [comment]
Yes, I have added this feature request to the [Roadmap](https://github.com/360EntSecGroup-Skylar/excelize/wiki).

**Comment by xuri** [comment]
Hi @mbresson and @VioletEvergardenZ. Sorry for my late reply. I have added rich text support for this lib, now you set cell with rich text by the [`SetCellRichText`](https://github.com/360EntSecGroup-Skylar/excelize/blob/66d0272f6af59b5f0c97a304379a795420a43e8b/cell.go#L460) function.

**Comment by mbresson** [comment]
Thanks!
