### ISSUE TITLE
Setting a cell value using indices

### ISSUE THREAD

**Issue by cemremengu** [360EntSecGroup-Skylar/excelize#193]
Is there a way to set a cell value instead of using `A2` , `B1` etc ?

Something like `SetCellValue(x, y, value)` ?

Using `A2` , `B1` etc is not really convenient when inserting data with loops (or at least I dont know how to do it right :))

**Comment by xuri** [comment]
Thanks for your issue. Same as the issue #63, we can use the [`TitleToNumber()`](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#TitleToNumber) and [`ToAlphaString()`](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#ToAlphaString) functions to convert between worksheet column title and index.

**Comment by cemremengu** [comment]
Thanks this works! However, I wish there was a more transparent and obvious API for this 🤔 

I will submit a PR if you like

**Comment by gatuin** [comment]
I see this is marked as closed, but to me it doesn't solve the issue.
To process things in loops there is still the process needed of first building a string that has both the row and column in it (e.g. constructing 'B6' etc), for things like the set cell functions to then split those back out again into separate row and columns.
If, for example, pulling values from a source into a sheet over thousands of rows you end up doing stuff like

```
SetCell(... , fmt.Sprintf("A%d",row), ...)
SetCell(... , fmt.Sprintf("B%d",row), ...)
SetCell(... , fmt.Sprintf("C%d",row), ...)
```

etc

instead of

```
SetCellXY(..., "A", row, ...)
SetCellXY(..., "B", row, ...)
SetCellXY(..., "C", row, ...)
```
being able to pass in row and column as separate params (even if having to use ABC instead of 123 for columns) would be a lot simpler for calling code and must be more efficient than having to join the values only for the SetCell functions to parse and split them back out again every time.

Basically a set of functions that mirror the existing SetCell functions with a SetCellXY variant (replacing the axis param with separate row and column params)
