### ISSUE TITLE
Loss Print Setup after function CopySheet()

### ISSUE THREAD

**Issue by LianAFei** [360EntSecGroup-Skylar/excelize#272]
After I use NewSheet and CopySheet function,Vertical print turn to  Horizontal print,How can I solve it with excelize. @xuri Thanks.

**Comment by xuri** [comment]
Thanks for your issue. Please provide file attachments and source code If you can.

**Comment by LianAFei** [comment]
func Excel() {
	xlsx, err := excelize.OpenFile("./test.xlsx")
	if err != nil {
		fmt.Println(err)
		return
	}
	newsheet := xlsx.NewSheet("第2页")
	err = xlsx.CopySheet(1, newsheet)
	if err != nil {
		fmt.Println(err)
	}
	err = xlsx.SaveAs("./test1.xlsx")
	if err != nil {
		fmt.Println(err)
	}
}
[test.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/2414111/test.xlsx)
[test1.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/2414112/test1.xlsx)
test.xlsx is the souce file.
test1.xlsx is the file after used Excel().
You can see the SheetName "第二页" turn into Horizontal print,but the Sheetname"第一页" is Vertical print.

**Comment by LianAFei** [comment]
@xuri Thanks.

**Comment by xuri** [comment]
Temporarily comment out this line [sheet.go#L472](https://github.com/360EntSecGroup-Skylar/excelize/blob/3e004d900b103379c2d62657a3070de4a2e8585a/sheet.go#L472), it will be works well. To avoid association modifications caused by incomplete copies, `CopySheet()` just implemented the copy of the cell value, not support copy the external associated elements and related content (such as pictures, tables, page orientaion, etc.,) currently, and there is still a lot of work to be done.

**Comment by LianAFei** [comment]
Ok Thank you @xuri
