### ISSUE TITLE
Write to file as stream row by row?

### ISSUE THREAD

**Issue by Ryouku** [360EntSecGroup-Skylar/excelize#29]
Hi,
would it be possible to have something like stream-writing to a file in case of lots of rows? Like hitting the excel sheet row limit?

I'm not so familiar with GoLang's IO, but maybe there is no problem to achieve this? 

For example I have millions of rows to put in excel sheets, and it is obviously memory heavy task. The idea is to read slice of rows from data source, like 100,000 at the time, then write them to the excel file in a loop until all rows was written. In such case there would be produced either excel file with few sheets or few excel files.

The primary idea is to handle memory consumption to reasonable amounts of RAM, like few gigabytes not tens..

What's Your opinion?

**Comment by Luxurioust** [comment]
@Ryouku Thanks for your issue. As a performance problem, I think this problem can be linked with issue #20 and #26. Next I would like to design a streaming interface to solve this problem.

**Comment by Ryouku** [comment]
Thanks!

**Comment by beezir** [comment]
Regarding low-hanging fruit for performance - I was having issues outputting a few thousand rows with roughly 30-40 columns each in any sort of reasonable time.  I narrowed it down and it appears the performance problems are coming from changes made in this commit (fixing missing hyperlink): https://github.com/Luxurioust/excelize/commit/6e1475a2429b2088a4c0b322962fc584370653d9#diff-ec4216644fd4919ab5c2a68efb70d453

That change causes the entire spreadsheet data structure to be fully rebuilt every time cell data is set instead of appending new rows when needed.  I haven't had time to dive into exactly what was fixed with that issue which is why I'm not submitting a pull request right now, but if I use a version of completeRow similar to the one prior to that commit, my time for xslx generation goes from upwards of a couple minutes to about 3 seconds with identical output (20,000 rows, 30 columns).  It still slows down quite a bit at higher numbers, but it's a target for massive improvement in the lower ranges as a starting point.

**Comment by sg871013613** [comment]
why？




发自网易邮箱大师


On 03/30/2017 11:33，Dave Butler<notifications@github.com> wrote：

Regarding low-hanging fruit for performance - I was having issues outputting a few thousand rows with roughly 30-40 columns each in any sort of reasonable time. I narrowed it down and it appears the performance problems are coming from changes made in this commit (fixing missing hyperlink): 6e1475a#diff-ec4216644fd4919ab5c2a68efb70d453

That change causes the entire spreadsheet data structure to be fully rebuilt every time cell data is set instead of appending new rows when needed. I haven't had time to dive into exactly what was fixed with that issue which is why I'm not submitting a pull request right now, but if I use a version of completeRow similar to the one prior to that commit, my time for xslx generation goes from upwards of a couple minutes to about 3 seconds with identical output (20,000 rows, 30 columns). It still slows down quite a bit at higher numbers, but it's a target for massive improvement in the lower ranges as a starting point.

**Comment by Luxurioust** [comment]
@beezir Thanks for your reminder. I have made some optimize, remove redundant XML element checking logic. The benchmark report of the current version of this library is shown on the [wiki page](https://github.com/Luxurioust/excelize/wiki).

**Comment by mewben** [comment]
+1 to this. Is there a way to send the result by row? I experienced around 5-10 minutes creating and downloading a 2MB xlsx file having 1000+ rows.

**Comment by Ryouku** [comment]
Hey @Luxurioust, any update?

**Comment by Luxurioust** [comment]
@Ryouku Yes, I have optimized the memory usage when parsing large file. Please upgrade the library to the last version.

**Comment by Ryouku** [comment]
Thanks! Will give it a shot.

**Comment by pjmuller** [comment]
Hi xuri,

I've gone through the multiple github issues related to performance / memory management. However I did not figure out if the following is already possible.

Situation: Having to write > 100.000 lines.
Preferred solution: have an io interface which periodically will write to disk so that memory consumption does go through the roof.

Does this exist and give you a snippet demonstrating this? Would also be nice for the standard documentation.

**Comment by pjmuller** [comment]
@xuri Can you check my comment above?

**Comment by cemremengu** [comment]
This is really causing issues... 😢 Memory usage goes off the roof

Any updates?

**Comment by duffiye** [comment]
Any updates?

**Comment by xuri** [comment]
Hi all, @Ryouku, @beezir, @mewben, @pjmuller, @kharism, @cemremengu, @duffiye Sorry for my late reply. I have added a [stream writer](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.NewStreamWriter) for generating a new worksheet with huge amounts of data.
