### ISSUE TITLE
How to view doc for v2.0.0?

### ISSUE THREAD

**Issue by dolmen** [360EntSecGroup-Skylar/excelize#431]
How can I view API documentation for v2.0.0?

Both godoc.org and go 1.12's godoc don't support Go modules. They only show v1.x.

**Comment by xuri** [comment]
Hi @dolmen, [GoDoc](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize) generates the document based on the code of the current master branch, and I created the [documentation website](https://xuri.me/excelize) to describe different versions of the API.

**Comment by AngangGuo** [comment]
The document (https://xuri.me/excelize/en/) says `Last version: v2.0.1`. Does that mean it's for new version > v2.0.0. 
Should we use `github.com/360EntSecGroup-Skylar/excelize/v2` instead of `github.com/360EntSecGroup-Skylar/excelize` on the following page? https://xuri.me/excelize/en/base/installation.html#install

**Comment by dolmen** [comment]
@AngangGuo That doc is outdated: it is for `v1`.

Use `github.com/360EntSecGroup-Skylar/excelize/v2` in your `import`.
Build your project as a Go module (`go mod init`) and set `GO11MODULE=on` for all `go` tasks for this project. With Go modules you don't have to explicitely `go get`: it will be automatic on `go build`.

**Comment by xuri** [comment]
Check docs for each released versions on [pkg.go.dev](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2?tab=versions).
