### ISSUE TITLE
Development - go.mod and gitignore

### ISSUE THREAD

**Issue by mlh758** [360EntSecGroup-Skylar/excelize#466]
**Description**

The go.mod seems to be out of sync with the project, every time I build it for tests it is modified:

```
golang.org/x/image v0.0.0-20190802002840-cff245a6509b
```

Also, I would like to update the gitignore to ignore the test files that get generated during the test suites execution. Would you accept a PR that updated the gitignore and go.mod?

**Comment by dolmen** [comment]
Modification of `.gitignore` should be a separate PR.

**Comment by mlh758** [comment]
Separate PRs for updating `.gitignore` and the mod file?

**Comment by dolmen** [comment]
Yes. `.gitignore` in one commit in one PR.
For `go.mod`+`go.sum`, I think that should be the job of the maintainer because (s)he should know better what the minimum version of the dependencies are supported.

Note that I'm not the maintainer. Just a contributor that follows the project for two years now and uses it in production code.

**Comment by bvwells** [comment]
On top of this, building master brings in v1 of the module due to incorrect import paths in test code. See #480.
