### ISSUE TITLE
 Call GetSheetName can not get correct sheetname

### ISSUE THREAD

**Issue by virteman** [360EntSecGroup-Skylar/excelize#485]
**Description**

GetSheetName can not get correct sheet name just return empty string

**Steps to reproduce the issue:**
1. my xlsx file's first sheet named "basic". so I call GetSheetIndex("basic") get return value is 15
2. call GetSheetName(15) return value is "" (empty string)

**Describe the results you received:**
I get an empty string as sheetname

**Describe the results you expected:**
I expect the return string should be "basic"

**Output of `go version`:**

```text
go version go1.11 linux/amd64
```

**Excelize version or commit ID:**

```text
eef232f09ecd41b1f8fc199906ce0be64865802e
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
```text
Ubuntu 18.04, wps 2019( can open and eidt excel 2007 xlsx file), thinkpad x1 carbon
```

**Comment by xuri** [comment]
Hi @virteman, thanks for your feedback. Could you provide testing file attachment?

**Comment by mlh758** [comment]
This is likely related to the changes I made [here](https://github.com/360EntSecGroup-Skylar/excelize/commit/faaaa52cb862499454a7f893b92e8430d00172a5) since the old method of using SheetID was causing the bug in #457 

It looks like we need to update [GetSheetIndex](https://github.com/360EntSecGroup-Skylar/excelize/blob/master/sheet.go#L298) to actually return the index rather than the SheetID since SheetID isn't a reliable index.

**Comment by mariaefi29** [comment]
Dear developers,

Do you have any updates on the issue? 

I have just moved to your package from another xlsx parser and when started testing on real data, it turned out it doesn't work for a lot of files.

For instance, I have a file with the only one sheet. I would like to get that sheet and I use file.GetSheetName(1), assuming that the sheet's name will return to me. Unfortunately, it returns an empty string. I dig deeper and I realised that the only one sheet I have in that file has index 2 (it's SheetID is 2). That's weird. As you said, for some reason it seems that SheetID isn't reliable index, but it has 'rId1' real id.

Could you please clarify that and/or give us some ETA on the fix? I used the latest version v2.1.0.

You can get the file here (I filled it up with the fake data).
[file to download](https://drive.google.com/file/d/1oJBcC7JPgWc_KWwmJR8LEn3_DIo_CoGt/view?usp=sharing)

We would be grateful you could look into that.

**Comment by xuri** [comment]
Hi @mariaefi29, thanks for your feedback, the ID returned by `GetSheetMap`  doesn't represent the order of the worksheet in the workbook. It just a reliable identifier, which can be used to set the active worksheet. Indeed, we couldn't get the order of worksheet in Excelize 2.1.0 currently, I plan to add a new API  named `GetSheetList` in the next version to solve this issue.

**Comment by mariaefi29** [comment]
@xuri,

Thank you for your reply! Very confusing :) Could you please advice us what to do? How can we get the only one sheet in excel file if we don't know the name of the sheet?`f.GetSheetName(f.GetActiveSheetIndex())`?

**Comment by mlh758** [comment]
Right now it's inconsistent, per [my comment above](https://github.com/360EntSecGroup-Skylar/excelize/issues/485#issuecomment-549847405). I had implemented a partial fix which was moving everything to be index based but missed a couple parts of the API. It's been a while since I looked at this but I think Xuri decided to roll back my change in #486  and make everything work off the SheetID instead.

**Comment by mariaefi29** [comment]
Dear developers,

Thank you for your replies!

@xuri Do you have any ETA on `GetSheetList`? We would appreciate it!

**Comment by xuri** [comment]
The `GetSheetList` will be released in the next version [2.2.0](https://github.com/360EntSecGroup-Skylar/excelize/projects/6) on May 11th, 2020.

**Comment by mariaefi29** [comment]
Thank you for this information!

**Comment by mariaefi29** [comment]
Would you like to consider change naming for major release version later? Index implies that there be some kind of an order. Sheet's index seems like really a sheet's number, not an identifier, even though it can be an identifier. But id may not be index.

**Comment by xuri** [comment]
Yeas. In the existing version, the "Index" of the API is actually an "ID", the next version will use a real index instead of an ID. The following functions will be affected:

```text
GetSheetName
GetSheetIndex
GetActiveSheetIndex
SetActiveSheet
```

**Comment by mariaefi29** [comment]
Cool! Thanks!

**Comment by xuri** [comment]
Hi @mariaefi29, I have added a new function `GetSheetList` and make existing API using the worksheet index in the list order. You can upgrade to the master branch code before the version released.

**Comment by mariaefi29** [comment]
Dear @xuri,

Thank you very much! I have tested it on the files from my flow and everything worked as expected!
