### ISSUE TITLE
Too much memory

### ISSUE THREAD

**Issue by PengWuLin** [360EntSecGroup-Skylar/excelize#494]
**Description**
Too much memory

**Steps to reproduce the issue:**
1.Create a new file。
2.Write a million pieces of data。
3.Analysis memory。

**Describe the results you received:**
Will occupy at least 2G of memory
**Describe the results you expected:**
Minimum memory footprint
**Output of `go version`:**
1.12.5
```text
(paste your output here)
```
![image](https://user-images.githubusercontent.com/39291860/65870988-10f8c980-e3b0-11e9-849e-0c4fc663dc80.png)

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by mlh758** [comment]
Could you paste some test code that you used to write the file? It would be helpful for anyone working on this to be starting from the same benchmarks.

**Comment by PengWuLin** [comment]
```package main

import (
	"fmt"
	"github.com/360EntSecGroup-Skylar/excelize"
)

func main() {

	f := excelize.NewFile()
	s:="This is test data"
	for row:=0;row<=1000000;row++{
 		for col:=0;col<=20;col++{
 			f.SetCellDefault("Sheet1",ColAndNumToAxis(col,row),s)
		}
	}
	// Save xlsx file by the given path.
	err := f.SaveAs("./test.xlsx")
	if err != nil {
		fmt.Println(err)
	}
}

func NumToString(columnIndex int)string{
	if columnIndex<0{
		return ""
	}
	if columnIndex==0{
		return "A"
	}
	if columnIndex<26{
		return string(columnIndex%26+64)
	}

	columnStr:=""

	if columnIndex>0{
		columnIndex--
		columnStr=string(columnIndex%26+65)+columnStr
		columnIndex=((columnIndex-columnIndex%26)/26)

	}
	return columnStr
}

func ColAndNumToAxis(colnum ,rownum int)string{
	return fmt.Sprintf("%s%d",NumToString(colnum),rownum)
}```

**Comment by PengWuLin** [comment]
> Could you paste some test code that you used to write the file? It would be helpful for anyone working on this to be starting from the same benchmarks.

```package main

import (
	"fmt"
	"github.com/360EntSecGroup-Skylar/excelize"
)

func main() {

	f := excelize.NewFile()
	s:="This is a test data"
	for row:=0;row<=1000000;row++{
 		for col:=0;col<=20;col++{
 			f.SetCellDefault("Sheet1",ColAndNumToAxis(col,row),s)
		}
	}
	// Save xlsx file by the given path.
	err := f.SaveAs("./test.xlsx")
	if err != nil {
		fmt.Println(err)
	}
}

func NumToString(columnIndex int)string{
	if columnIndex<0{
		return ""
	}
	if columnIndex==0{
		return "A"
	}
	if columnIndex<26{
		return string(columnIndex%26+64)
	}

	columnStr:=""

	if columnIndex>0{
		columnIndex--
		columnStr=string(columnIndex%26+65)+columnStr
		columnIndex=((columnIndex-columnIndex%26)/26)

	}
	return columnStr
}

func ColAndNumToAxis(colnum ,rownum int)string{
	return fmt.Sprintf("%s%d",NumToString(colnum),rownum)
}

func StringToNum(colnum string)int  {
	result:=0
	length:=len(colnum)
	for i:=0;i<length;i++{
		num:=int(colnum[length-i-1]-'A'+1)
		num*=int(math.Pow(26,float64(i)))
		result+=num
	}
	return result
}
```

**Comment by mlh758** [comment]
I switched it over to v2 since that has some performance improvements, although mostly on the read side:

```
package main

import (
	"fmt"

	"github.com/360EntSecGroup-Skylar/excelize/v2"
)

func main() {
	MakeFile()
}

func MakeFile() {
	f := excelize.NewFile()
	s := "This is a test data"
	for row := 1; row <= 1000000; row++ {
		for col := 1; col <= 20; col++ {
			f.SetCellDefault("Sheet1", cellName(col, row), s)
		}
	}
	// Save xlsx file by the given path.
	err := f.SaveAs("./test.xlsx")
	if err != nil {
		fmt.Println(err)
	}
}

func cellName(col, row int) string {
	val, err := excelize.CoordinatesToCellName(col, row)
	if err != nil {
		panic(err)
	}
	return val
}
```

Here is the memory profile:

![mem](https://user-images.githubusercontent.com/4331955/67682670-e756a200-f95d-11e9-8f24-cf46f31ae4ee.png)

A lot of time is spent in the xml encoder, which we probably can't avoid. However `fillColumns` and `trimCell` appear to be good candidates for optimization.

**Comment by mlh758** [comment]
Using the benchmark I made for this I made a couple changes to excelize and got these results:

Baseline:
BenchmarkMakeFile-8   	       1	71283356886 ns/op	21451017832 B/op	189006091 allocs/op
Check in trimCell:
BenchmarkMakeFile-8   	       1	69635513419 ns/op	18763016472 B/op	188006095 allocs/op
With size hint:
BenchmarkMakeFile-8   	       1	63976723193 ns/op	13435011584 B/op	183006040 allocs/op

Benchmark I made for reference:
```
package main

import (
	"testing"
)

func BenchmarkMakeFile(b *testing.B) {
	for i := 0; i < b.N; i++ {
		MakeFile()
	}
}
```

The changes:
https://github.com/mlh758/excelize/commit/ac79acd59ddfd0272b959a86e2545be3f52b0e94

I made `trimCell` check if the row was already completely populated before allocating a new row and copying data over. This should add very little CPU overhead in most situations, scanning a row is pretty cheap and the maximum row size is about 65,000 items which I doubt many users have. I could add an if check to short circuit the loop if any un-populated item is found so it can continue but that might slow it down in the normal case of only having 10-50 columns.

I am using the last populated row in the document to set the size for the newly added row. My guess here is that most spreadsheets are relatively rectangular so this should be a decent guess at the size of the next row. In the documents we generate this is certainly the case, except for a few rows per sheet with heading information. A worst-case scenario for this is someone who is generating a document that is shaped like this:
30 columns
1 column
30 columns
1 column

since that would consistently over/under allocate memory for the rows. That seems like a strange thing to do though, and is probably much rarer than the current problem of consistently under-allocating for rectangular sheets. If we run into this problem we could keep a running mean of row size and use that instead.

@xuri what do you think of the commit I have and the reasoning behind it? Should I open a PR?

**Comment by mlh758** [comment]
Also @PengWuLin would you be willing to try the commit I linked above and see if that makes a difference in your use case?

**Comment by PengWuLin** [comment]
> Also @PengWuLin would you be willing to try the commit I linked above and see if that makes a difference in your use case?

@mlh758 Thank you，I'll test it
