### ISSUE TITLE
SetSheet?

### ISSUE THREAD

**Issue by sowhyim** [360EntSecGroup-Skylar/excelize#614]
i saw `SetSheetRow(sheet, axis string, slice interface{})`.

why not SetSheetRow(sheet, axis string, slice [][]interface{})

**Comment by xuri** [comment]
`SetSheetRow` writes an array to a single row, please call `SetSheetRow` in the traverse of the source data

**Comment by sowhyim** [comment]
I mean:
if axis=A1 and slice=[3][3]interface
then this sheet should set from A1 to C3

**Comment by xuri** [comment]
The `SetSheetRow` API used for setting cells in a single row for the worksheet, if the `slice` parameter's data type changed to `[][]interface{}`, the function name should be `SetSheetRows` instead of `SetSheetRow`. However, due to the principle of minimum availability, I don't recommend adding it. if you have any questions, please let me know.
