### ISSUE TITLE
api更改导致我们的项目全部构建失败了 (API changed)

### ISSUE THREAD

**Issue by Disac** [360EntSecGroup-Skylar/excelize#74]
我们想知道更改api的原因

**Comment by Disac** [comment]
为什么没有保留旧的api，可以注释废弃的啊

**Comment by dlintw** [comment]
It is better to mark a 'tag', if it is not compatible with old API

**Comment by Luxurioust** [comment]
I apologize for the impact for your project, On commit [66e5d1f](https://github.com/Luxurioust/excelize/commit/66e5d1fa801680f87a647a968fd4965ef9668b9a) I have to rename the function `CreateFile()` to `NewFile()` for making more concise name and rename `WriteTo()` to `SaveAs()` because it collides with the `WriterTo` interface in [`io`](https://golang.org/pkg/io/#WriterTo) package. Please check the commit log before update the library to ensure compatibility with existing applications.
