### ISSUE TITLE
Add options to outline groups / set them hidden

### ISSUE THREAD

**Issue by Amodio** [360EntSecGroup-Skylar/excelize#791]
**Description**
Hello,

I am trying to hide grouped columns automatically, having them set to an outline level.
XlsxWriter allows options to hide/collapse these outlines; would it be possible to have the same feature?

Thank you for your work!

**Comment by xuri** [comment]
Thanks for your issue. I'll add set collapse col/row support recently.

**Comment by xuri** [comment]
After evaluation, I don't decide to add a new API or change the existing API to support this feature, because we can expand or collapse data in the outline by `SetRowVisible` and `SetColVisible`. For example create 3 outlines on the `Sheet1`, expand outline `B:P` on level 1, collapsed outline `D:F` on level 2 and  expand outline `B:P` on level 2:

```go
colOutlines := [][]int{{2, 3, 1}, {4, 5, 2}, {6, 7, 1}, {8, 12, 2}, {13, 15, 1}}
for _, outline := range colOutlines {
    for col := outline[0]; col <= outline[1]; col++ {
        colName, _ := excelize.ColumnNumberToName(col)
        if err := f.SetColOutlineLevel("Sheet1", colName, uint8(outline[2])); err != nil {
            fmt.Println(err)
            return
        }
    }
}
// for expand columns: set width and visiable (last column of the collapse outline shoud be visiable)
if err := f.SetColVisible("Sheet1", "B:C", true); err != nil {
    fmt.Println(err)
    return
}
if err := f.SetColVisible("Sheet1", "F:O", true); err != nil {
    fmt.Println(err)
    return
}
colWidth, _ := f.GetColWidth("Sheet1", "A")
if err := f.SetColWidth("Sheet1", "B", "C", colWidth); err != nil {
    fmt.Println(err)
    return
}
if err := f.SetColWidth("Sheet1", "F", "O", colWidth); err != nil {
    fmt.Println(err)
    return
}
```

![expand or collapse data in the outline by Excelize](https://user-images.githubusercontent.com/2809468/110007197-667b9780-7d55-11eb-931b-72445dcd5eb9.png)
