### ISSUE TITLE
Is There a method to get total col count or row count quickly?

### ISSUE THREAD

**Issue by eaglexiang** [360EntSecGroup-Skylar/excelize#817]
like [Sheet.Dimension](https://pkg.go.dev/github.com/plandem/xlsx@v1.0.4?utm_source=gopls#Sheet.Dimension) of pkg github.com/plandem.

I'm working on move our excel handle mod from plandem to excelize recently. Sometimes pre-checking total count is necessary to avoid waste of time and storage. Is there a typical way?

**Comment by xuri** [comment]
It may not be accurate to use the dimension property to get the total row and column for some spreadsheets, so traverse [row](https://xuri.me/excelize/en/sheet.html#Rows) and [column](https://xuri.me/excelize/en/sheet.html#Cols) and count by the iterator will be a better way.

**Comment by eaglexiang** [comment]
OK. Thank you for reply.

**Comment by rbucker** [comment]
> It may not be accurate to use the dimension property to get the total row and column for some spreadsheets, so traverse [row](https://xuri.me/excelize/en/sheet.html#Rows) and [column](https://xuri.me/excelize/en/sheet.html#Cols) and count by the iterator will be a better way.

this does not make sense since there is getrows() and getcols() that produces a 2D array with presumably the data. Clearly there are complicates when cells are merged... however the bigger use-case is exporting the xlsx to csv... and in that case there is a max col and max row regardless of "sparse cells".

** take a lesson from me... call getrows() and/or getcols() once and safe the results in variable. (in my first attempt I called the function in the for loop condition and it never completed and in one case I ran out of RAM.

**Comment by eaglexiang** [comment]
> ** take a lesson from me... call getrows() and/or getcols() once and safe the results in variable. (in my first attempt I called the function in the for loop condition and it never completed and in one case I ran out of RAM.

Yes it do cause out of RAM, our solution is limit of range loop of `Rows`, it works.
