### ISSUE TITLE
Issue with latest release 

### ISSUE THREAD

**Issue by ahamansh** [360EntSecGroup-Skylar/excelize#836]
when trying to run continues error
go/pkg/mod/github.com/360!ent!sec!group-!skylar/excelize/v2@v2.4.0/calc.go:1836:18: undefined: strconv.ParseComplex

**Comment by xuri** [comment]
This issue duplicates with #815 and #820, since commit [`f8f699`](https://github.com/360EntSecGroup-Skylar/excelize/commit/f8f699a172bd0219a8736b19091dd3eaa9eb3b25), for complex number support required, the requirements Go language version is 1.15 or later. If your using the Go version is 1.10 or later but under 1.15 please using the v2.3.2 version.
