### ISSUE TITLE
as row sum grows, it slows down obviously...

### ISSUE THREAD

**Issue by binnnliu** [360EntSecGroup-Skylar/excelize#94]
There is For loop in every SetCellValue, so as row sum grows, it slows down obviously...

**Comment by xuri** [comment]
As you said, in order to ensure the compatibility of some complex patterns currently(charts, table, formula, pivot and etc.), Excelize do a lot of checks, that will be impacted on performance, generates large files will be very slow. Reference performance figures on the [wiki](https://github.com/360EntSecGroup-Skylar/excelize/wiki).

**Comment by cemremengu** [comment]
I have an excel with around 150,000 rows and it is very very slow (does not finish even in 15-20mins). Is this normal? Is there a tuning we can make to disable the checks like mentioned in the wiki?

I think it's good to disable all checks and leave it to the user when desired.

**Comment by binnnliu** [comment]
@cemremengu you can try `https://github.com/tealeg/xlsx`, and it fast.
